### Numpy
    Numeric Python의 약자
    수학분야 관련 통계 연산 작업시 사용
    과학 계산 컴퓨팅, 데이터 분석에 필요한 기본적인 패키지
    
    Numpy배열은 리스트와 거의 흡사
    리스트보다 훨씬 빠르고 메모리 효율성이 높아서 성능상 우위를 차지한다.
    
    Numpy는 사용에 앞서서 import해서 사용해야 한다.
    Numpy 배열 만드는 방법
    1) array() 사용
    2) random 모듈의 랜덤함수 사용

In [1]:
import numpy as np

## np 배열 생성 
### 리스트와 비교
    array() 함수 사용

In [10]:
myList = [4,5,6,7]
myArr = np.array(myList)

print(myList)
print(myArr)

print(type(myList))
print(type(myArr))

'''
ndarray는 출력 결과 [ ] 안에 값들이 나열되지만 ,로 구분되진 않는다.
ndarray타입
ndarray 클래스는 다차원 행렬구조를 지원하는 Numpy의 핵심 클래스

'''
myList_sub = myList[1:3]
print(myList_sub)

myArr_sub = myArr[1:3]
print(myArr_sub)

myList_sub[0] = -5
myArr_sub[0] = -5
print(myList_sub)
print(myArr_sub)

print("*" * 30)

'''
리스트는 원본이 안 바뀐다. 변경되면 기존의 것을 카피해놓고 새로운 것을 만든다.
반면에 np배열은 원본뷰가 바뀌어버린다.
이것이 리스트와 np배열의 가장 큰 차이점이다.
메모리 효율성과 연관되는 부분이다.
'''

print(myList) # list => 원본이 안 바뀐다.
print(myArr) # np배열 => 원본이 바뀐다.

[4, 5, 6, 7]
[4 5 6 7]
<class 'list'>
<class 'numpy.ndarray'>
[5, 6]
[5 6]
[-5, 6]
[-5  6]
******************************
[4, 5, 6, 7]
[ 4 -5  6  7]


### np.random 사용하기

#### rand() 함수 사용하기

In [12]:
a = np.random.rand(5)
print(a)
print(type(a))

[0.88049062 0.11804139 0.23027837 0.38924963 0.64961181]
<class 'numpy.ndarray'>


#### randint() 함수 사용하기

In [17]:
b = np.random.randint(1,10,5)
print(b)
print(type(b))

[4 2 1 6 1]
<class 'numpy.ndarray'>


#### randn() 함수 사용하기
    가우시안 표준분포에 해당하는 값을 뽑아냄

In [18]:
c = np.random.randn(10)
print(c)
print(type(c))

[-0.90998277 -0.06878845  1.72072705  1.12136733 -0.89303558 -1.38616033
  2.05390119  0.15333402  0.86693588  0.31979775]
<class 'numpy.ndarray'>


### np배열의 초기화
    zeros(), ones(), arange()...함수를 이용해서 배열 생성과 동시에 특정한 값으로
    초기화할 수 있다.

In [30]:
# 1.
az = np.zeros(10)
print(az)

#2. 1값으로 이뤄진 크기가 10인 배열 생성
ao = np.ones(10)
print(ao)

#3. 3 by 3 단위의 배열 생성(대각선에는 1)
ae = np.eye(3)
print(ae)

#4. arange()
print(np.arange(3))
print(np.arange(3,7))
print(np.arange(3,10,2))

print("*"*30)

a7 = np.zeros(10)+7
print(a7)

af = np.full((5,5),-11)
print(af)

af = np.full((7,5),23)
print(af)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[0 1 2]
[3 4 5 6]
[3 5 7 9]
******************************
[7. 7. 7. 7. 7. 7. 7. 7. 7. 7.]
[[-11 -11 -11 -11 -11]
 [-11 -11 -11 -11 -11]
 [-11 -11 -11 -11 -11]
 [-11 -11 -11 -11 -11]
 [-11 -11 -11 -11 -11]]
[[23 23 23 23 23]
 [23 23 23 23 23]
 [23 23 23 23 23]
 [23 23 23 23 23]
 [23 23 23 23 23]
 [23 23 23 23 23]
 [23 23 23 23 23]]


### np배열과 리스트의 차이점
    1. np배열은 원본을 바로 바꿈으로써 메모리 효율성이 뛰어나다
    2. 리스트는 여러가지 자료형이 원소로 올 수 있지만
       np배열은 한가지 자료형만 원소로 쓰일 수 있다.

In [35]:
# 리스트는 자료형 구조로 서로 다른 자료형이 원소로 올 수 있다.
L = [1,2,3,'4',4,'하바리']
print(L)
print(type(L))

# np.array는 하나의 자료형만 저장 가능
A = np.array(L)
print(A)
print(type(A))
# capa가 더 큰 자료형으로 변환
A2 = np.array([1.6,3,8,3])
print(A2)

A3 = np.array([1,2,3,4], dtype="float")
print(A3)

A4 = np.array([1,2,3,4], dtype=np.float64)
print(A4)

[1, 2, 3, '4', 4, '하바리']
<class 'list'>
['1' '2' '3' '4' '4' '하바리']
<class 'numpy.ndarray'>
[1.6 3.  8.  3. ]
[1. 2. 3. 4.]


### Numpy 배열에서 사용되는 함수, 속성
    ndim shape reshape() size type dtype astype()

In [37]:
arr1 = np.array([[1.0, 2,3],[4,5,6]], dtype = np.int32) # 속성인 dtype을 정수로 지정해주기
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [47]:
# 기능
print(type(arr1))
print(np.ndim(arr1)) # 매트릭스
print(np.shape(arr1)) # 몇행 몇열
print(np.size(arr1)) # 개수

# 속성
print("*"*30)
print(arr1.ndim)
print(arr1.shape)
print(arr1.size)
print(arr1.dtype)

print("*"*30)
# ndarray 안에 들어있는 모든 요소들의 타입을 한방에 바꿔버리는 기능...astype

arr1_1 = arr1.astype(np.float32)
print(arr1_1)

print("*"*30)
arr2 = np.arange(32)
print(arr2)

arr2_1 = np.arange(32).reshape(4,8)
print(arr2_1)

<class 'numpy.ndarray'>
2
(2, 3)
6
******************************
2
(2, 3)
6
int32
******************************
[[1. 2. 3.]
 [4. 5. 6.]]
******************************
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31]
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]]
