### 랜덤함수와 seed 값 설정하기
    seed값은 한번만 설정해주면 계속 적용된다.
    시드는 보통 현재시각 등을 이용해서 자동으로 정해지지만
    우리가 수동으로도 설정할 수 있다.
    특정한 시드값이 사용되면 그 다음에 만들어지는 난수들을 예측할 수 있다.

In [1]:
import numpy as np

In [3]:
np.random.seed(0) # 수동...(0포함 양의 정수)

arr1 = np.random.randn(4,4)
print(arr1)

[[ 1.76405235  0.40015721  0.97873798  2.2408932 ]
 [ 1.86755799 -0.97727788  0.95008842 -0.15135721]
 [-0.10321885  0.4105985   0.14404357  1.45427351]
 [ 0.76103773  0.12167502  0.44386323  0.33367433]]


In [5]:
arr2 = np.arange(1,10)
arr2

arr3 = np.arange(1,10).reshape(3,3)
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### 인덱싱, 슬라이싱

In [6]:
narray = np.arange(5)
narray

array([0, 1, 2, 3, 4])

In [9]:
# 1. 인덱싱, 슬라이싱으로 값 추출하기
print(narray[1], narray[4])
print(narray[1:5])
print(narray[:])
print(narray[2:4])

1 4
[1 2 3 4]
[0 1 2 3 4]
[2 3]


In [11]:
narray2 = np.random.randint(10,20,16).reshape(4,4)
narray2

array([[12, 17, 12, 10],
       [10, 14, 15, 15],
       [16, 18, 14, 11],
       [14, 19, 18, 11]])

In [32]:
# 1) narray2 중에서 첫번쨰 행의 세번째 값 12를 가져오려면?
narray2[0][2]
narray2[0,2]

# 2) 2번째 라인 [10,14,15,15] 전체를 출력
narray2[1:2,0:4]
#narray2[1:2,:]
#narray2[1,:]
narray2[1,0:]

# 3) 전체 행에 대해서 4번째 열을 출력?
narray2[0:4, 3:4]
narray2[:, 3:]
narray2[:,3]

# 4) 전체 행에 대해서 1,2번째까지의 열을 출력
narray2[:,:2]

array([[12, 17],
       [10, 14],
       [16, 18],
       [14, 19]])

### 인덱싱과 조건 슬라이싱

In [36]:
arr1
# 1. 논리연산자 사용해서 값을 받아오거나 값을 변경

arr1[arr1>0]
arr1[arr1<0]
arr1[arr1<0] = 0
# 원본도 함꼐 바뀐다...
arr1

array([[1.76405235, 0.40015721, 0.97873798, 2.2408932 ],
       [1.86755799, 0.        , 0.95008842, 0.        ],
       [0.        , 0.4105985 , 0.14404357, 1.45427351],
       [0.76103773, 0.12167502, 0.44386323, 0.33367433]])

In [37]:
# 2. where 함수
arr1_1 = np.where(arr1>0,arr1,-1)
arr1_1

array([[ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ],
       [ 1.86755799, -1.        ,  0.95008842, -1.        ],
       [-1.        ,  0.4105985 ,  0.14404357,  1.45427351],
       [ 0.76103773,  0.12167502,  0.44386323,  0.33367433]])

In [38]:
# 3. 1,2를 가지고 응용하기
arr2 = np.array([[1,2],[3,4],[5,6]])
arr2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [40]:
# 논리연산자 2보다 큰 수만 출력 되도록
bool_idx = arr2>2
print(arr2[bool_idx])

[3 4 5 6]


### 통계 함수
    sum, mean, min, max, argmin, argmax, cumsum

In [43]:
narray2

array([[12, 17, 12, 10],
       [10, 14, 15, 15],
       [16, 18, 14, 11],
       [14, 19, 18, 11]])

In [44]:
np.sum(narray2)

226

In [46]:
print(np.sum(narray2,axis=1)) #열
print(np.sum(narray2,axis=0)) #행

[51 54 59 62]
[52 68 59 47]
